# Define our project container
php-webserver:
  # Define that the Dockerfile required to build the image of this container
  # is located in the same directory as this docker-compose.yml file
  build: .
  # Forward port 80 on this image to port 8080 on localhost
  ports:
    - 8080:80
